name: Build and deploy .NET Core application to Web App eventifyTn

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: eventifyTn
  AZURE_WEBAPP_PACKAGE_PATH: eventify.API/publish
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: eventify.API

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    - name: Publish Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # Required for OIDC
      contents: read    # Optional (needed for checking out code)
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Azure Login (OIDC)
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

    - name: Install EF Core CLI
      run: dotnet tool install --global dotnet-ef

    - name: Restore dependencies
      run: dotnet restore

    # Migrate AppIdentityDbContext
    - name: Create EF Bundle for Identity DB
      run: |
        dotnet ef migrations bundle \
          --project ./eventify.Infrastructure/eventify.Infrastructure.csproj \
          --startup-project ./eventify.API/eventify.API.csproj \
          --output identity-migrate.exe \
          --context AppIdentityDbContext

    - name: Run Identity Migration Bundle
      run: ./identity-migrate.exe
      env:
        ConnectionStrings__Default: ${{ secrets.DEV_DB_CONNECTION_STRING }}

    # Migrate EventsDbContext
    - name: Create EF Bundle for Events DB
      run: |
        dotnet ef migrations bundle \
          --project ./eventify.Infrastructure/eventify.Infrastructure.csproj \
          --startup-project ./eventify.API/eventify.API.csproj \
          --output events-migrate.exe \
          --context EventsDbContext

    - name: Run Events Migration Bundle
      run: ./events-migrate.exe
      env:
        ConnectionStrings__Default: ${{ secrets.DEV_DB_CONNECTION_STRING }}