deploy:
  runs-on: ubuntu-latest
  permissions:
    id-token: write
    contents: read
  needs: build
  steps:
  - name: Download artifact from build job
    uses: actions/download-artifact@v4
    with:
      name: webapp
      path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  
  - name: Azure Login (OIDC)
    uses: azure/login@v2
    with:
      client-id: ${{ secrets.AZURE_CLIENT_ID }}
      tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  - name: Deploy to Azure WebApp
    uses: azure/webapps-deploy@v2
    with:
      app-name: ${{ env.AZURE_WEBAPP_NAME }}
      package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  
  - name: Checkout code
    uses: actions/checkout@v4

  - name: Setup .NET SDK
    uses: actions/setup-dotnet@v4
    with:
      dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

  - name: Install EF Core CLI
    run: dotnet tool install --global dotnet-ef

  # Migrate AppIdentityDbContext
  - name: Restore dependencies
    run: dotnet restore

  - name: Create EF Bundle for Identity DB
    run: |
      dotnet ef migrations bundle \
        --project ./eventify.Infrastructure/eventify.Infrastructure.csproj \
        --startup-project ./eventify.API/eventify.API.csproj \
        --output identity-migrate.exe \
        --context AppIdentityDbContext

  - name: Run Identity Migration Bundle
    run: ./identity-migrate.exe
    env:
      ConnectionStrings__Default: ${{ secrets.DEV_DB_CONNECTION_STRING }}

  # Migrate EventsDbContext
  - name: Create EF Bundle for Events DB
    run: |
      dotnet ef migrations bundle \
        --project ./eventify.Infrastructure/eventify.Infrastructure.csproj \
        --startup-project ./eventify.API/eventify.API.csproj \
        --output events-migrate.exe \
        --context EventsDbContext

  - name: Run Events Migration Bundle
    run: ./events-migrate.exe
    env:
      ConnectionStrings__Default: ${{ secrets.DEV_DB_CONNECTION_STRING }}